<Project>

	<Choose>
		<When Condition="$(MSBuildProjectName.Contains('Core')) Or $(MSBuildProjectName.Contains('Terminal'))">
			<ItemGroup>
				<Compile Update="**\*.cs">
					<DependentUpon>$([System.String]::Copy(I%(Filename).cs).Replace('Cached',''))</DependentUpon>
				</Compile>
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<Compile Update="Models\*.cs">
					<DependentUpon>$([System.String]::Copy(I%(Filename).cs).Replace('Cached',''))</DependentUpon>
				</Compile>
				<Compile Update="Models\*\*.cs">
					<DependentUpon>$([System.String]::Copy(I%(Filename).cs).Replace('Cached',''))</DependentUpon>
				</Compile>
			</ItemGroup>
		</Otherwise>
	</Choose>

	<ItemGroup>
		<Compile Remove="TestResults\**" />
		<EmbeddedResource Remove="TestResults\**" />
		<None Remove="TestResults\**" />
	</ItemGroup>

</Project>