<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <Choose>
    <!-- #region Project Libs -->
    <When Condition="$(MSBuildProjectName.EndsWith('.Core'))">
      <ItemGroup>
        <PackageVersion Include="EvilBaschdi.Core" Version="2026.3.30.19" />
        <PackageVersion Include="EvilBaschdi.Core.DependencyInjection" Version="2026.4.21.19" />
      </ItemGroup>
    </When>
    <When Condition="$(MSBuildProjectName.EndsWith('.Avalonia'))">
      <ItemGroup>
        <PackageVersion Include="EvilBaschdi.Core.Avalonia" Version="2026.5.11.6" />
      </ItemGroup>
    </When>
    <When Condition="$(MSBuildProjectName.EndsWith('.Wpf'))">
      <ItemGroup>
        <PackageVersion Include="EvilBaschdi.Core.Wpf" Version="2026.3.3.17" />
      </ItemGroup>
    </When>
    <When Condition="$(MSBuildProjectName.EndsWith('.Terminal'))">
      <ItemGroup>
        <PackageVersion Include="Spectre.Console" Version="0.55.2" />
      </ItemGroup>
    </When>
    <!-- #endregion Project Libs -->
    <!-- #region Unit Test Libs -->
    <When Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
      <ItemGroup>
        <PackageVersion Include="coverlet.collector" Version="10.0.0" />
        <PackageVersion Include="EvilBaschdi.Testing" Version="2026.4.28.17" />
        <PackageVersion Include="FluentAssertions.Analyzers" Version="0.34.1" />
        <PackageVersion Include="Meziantou.FluentAssertionsAnalyzers" Version="1.0.22" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
        <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
        <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
        <PackageVersion Include="xunit.analyzers" Version="1.27.0" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
      </ItemGroup>
    </When>
    <!-- #endregion Unit Test Libs -->
  </Choose>
</Project>