<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>About Window Avalonia</Description>
		<AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EvilBaschdi.About.Core\EvilBaschdi.About.Core.csproj" />
	</ItemGroup>

</Project>
